force-app/main/default/objects/Account/fields/Owlin_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Owlin_Entity_Id__c</fullName>
    <label>Owlin Entity Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Owlin_Entity_Requested_Id__c.field-meta.xml
<CustomField>
    <fullName>Owlin_Entity_Requested_Id__c</fullName>
    <description>This is batch id in which entity was requested to Owlin</description>
    <label>Owlin Entity Requested Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This configuration is used to maintain credentials and token for making a Owlin API calls</description>
    <label>Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Configuration_Settings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint to make a request</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Settings__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Field to store token to make API calls based on expiry date</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OwlinAccountsLinkQueue.cls
/**
 * Created by anshulagrawal on 2019-03-03.
 */

public with sharing class OwlinAccountsLinkQueue implements System.Queueable, Database.AllowsCallouts {

    private Set<Id> queuedAccountIds;
    private Configuration_Settings__c owlinConfiguration;
    String token;

    public OwlinAccountsLinkQueue(Configuration_Settings__c owlinConfiguration, Set<Id> queuedAccountIds, String token) {
        this.queuedAccountIds = queuedAccountIds;
        this.owlinConfiguration = owlinConfiguration;
        this.token = token;
    }

    /**
     * queueable execute method
     *
     * @param context
     */
    public void execute(System.QueueableContext context) {

        try {
            //handle queued transactions
            if (queuedAccountIds.size() > 0 && owlinConfiguration != null) {
                List<Account> accountsToLinkList = new List<Account>();
                //iterate accounts
                for (Account accountToLink : [
                        SELECT
                                id,Website,Name,Owlin_Entity_Id__c,Owlin_Entity_Requested_Id__c
                        from Account
                        where id in :queuedAccountIds
                ]) {
                    accountToLink.Owlin_Entity_Requested_Id__c = context.getJobId();
                    accountsToLinkList.add(accountToLink);
                }
                if (accountsToLinkList != null) {
                    //for updating with owlin entity id
                    Map<Id, Account> accountRequestedToLinkMap = new Map<Id, Account>(accountsToLinkList);
                    OwlinLinkEntitiesRequestWrapper requestWrapper = OwlinEntitiesHandler.prepareOwlinEntityLinkRequest(accountsToLinkList);
                    HttpResponse httpResponse;
                    if (requestWrapper != null) {
                        String body = Json.serialize(requestWrapper);
                        system.debug('body in OwlinAccountsLinkQueue >>' + body);
                        HttpClient client = new HttpClient();
                        String endpointString = 'https://' + owlinConfiguration.Endpoint__c + 'filters/suggest';
                        client.post(endpointString, body, token!=null ? token: owlinConfiguration.Token__c);
                        httpResponse = client.getHttpResponse();
                        if (httpResponse != null) {
                            String jsonResponse = httpResponse.getBody();
                            System.debug('jsonResponse in queue'+jsonResponse);
                            OwlinLinkEntitiesResponseWrapper apiResponse = OwlinLinkEntitiesResponseWrapper.parse(jsonResponse);
                            for (OwlinLinkEntitiesResponseWrapper.matches owlinEntity : apiResponse.matches) {
                                Id accountId = Id.valueOf(owlinEntity.original_id);
                                if (accountRequestedToLinkMap.containsKey(accountId)) {
                                    accountRequestedToLinkMap.get(accountId).Owlin_Entity_Id__c = owlinEntity.filter_id;
                                }
                            }
                        }
                        //updating accounts with filter ids
                        update accountRequestedToLinkMap.values();
                    }

                }
            }
        }catch (Exception e){
            system.debug('Exception occurred in queueable OwlinAccountsLinkQueue job '+e.getMessage());
        }
    }

}